export const ERROR_CODES = {
  VALIDATION_ERROR: "VALIDATION_ERROR",

  INSTALLATION_NOT_FOUND: "INSTALLATION_NOT_FOUND",

  FREE_DOWNLOAD_LIMIT_REACHED: "FREE_DOWNLOAD_LIMIT_REACHED",

  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
} as const;
